# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PyRL.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PyRL.proto',
  package='pyRL',
  syntax='proto3',
  serialized_options=_b('\n\004pyRLB\tPyRLProto'),
  serialized_pb=_b('\n\nPyRL.proto\x12\x04pyRL\"\x1b\n\x03Obs\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01v\x18\x02 \x01(\x05\"\x18\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32+\n\x04PyRL\x12#\n\x06getObs\x12\x0c.pyRL.Action\x1a\t.pyRL.Obs\"\x00\x42\x11\n\x04pyRLB\tPyRLProtob\x06proto3')
)




_OBS = _descriptor.Descriptor(
  name='Obs',
  full_name='pyRL.Obs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='pyRL.Obs.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v', full_name='pyRL.Obs.v', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=47,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='pyRL.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='pyRL.Action.action', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Obs'] = _OBS
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Obs = _reflection.GeneratedProtocolMessageType('Obs', (_message.Message,), {
  'DESCRIPTOR' : _OBS,
  '__module__' : 'PyRL_pb2'
  # @@protoc_insertion_point(class_scope:pyRL.Obs)
  })
_sym_db.RegisterMessage(Obs)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'PyRL_pb2'
  # @@protoc_insertion_point(class_scope:pyRL.Action)
  })
_sym_db.RegisterMessage(Action)


DESCRIPTOR._options = None

_PYRL = _descriptor.ServiceDescriptor(
  name='PyRL',
  full_name='pyRL.PyRL',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=75,
  serialized_end=118,
  methods=[
  _descriptor.MethodDescriptor(
    name='getObs',
    full_name='pyRL.PyRL.getObs',
    index=0,
    containing_service=None,
    input_type=_ACTION,
    output_type=_OBS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PYRL)

DESCRIPTOR.services_by_name['PyRL'] = _PYRL

# @@protoc_insertion_point(module_scope)
