# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import PyRL_pb2 as PyRL__pb2


class PyRLStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getObs = channel.unary_unary(
        '/pyRL.PyRL/getObs',
        request_serializer=PyRL__pb2.Action.SerializeToString,
        response_deserializer=PyRL__pb2.Obs.FromString,
        )


class PyRLServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getObs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PyRLServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getObs': grpc.unary_unary_rpc_method_handler(
          servicer.getObs,
          request_deserializer=PyRL__pb2.Action.FromString,
          response_serializer=PyRL__pb2.Obs.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pyRL.PyRL', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
